/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DAOsubScreens;

import DAO.PortafolioGestor;
import JPAControllers.exceptions.IllegalOrphanException;
import JPAControllers.exceptions.NonexistentEntityException;
import entity.Portafolios;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.eclipse.persistence.exceptions.DatabaseException;

/**
 *
 * @author 60044723
 */
public class PortafoliosForm extends javax.swing.JPanel {

    private final PortafolioGestor portafoliosGestor;
    private final DateFormat fecha_format;
    private Portafolios selectPortafolios;

    /**
     * Creates new form PortafoliosForm
     */
    public PortafoliosForm(PortafolioGestor p_portafoliosGestor) {
        initComponents();
        this.portafoliosGestor = p_portafoliosGestor;
        this.fecha_format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        this.fechainicial.setText(fecha_format.format(new Date()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        valorinicial = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fechainicial = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnverlista = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Portafolios");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombre");

        nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        valorinicial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Valor Inicial");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Fecha inicial");

        fechainicial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnguardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btncancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btncancelar.setText("Cancelar");

        tabla.setModel(fill_table());
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        tabla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        btnverlista.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        btnverlista.setText("Ver lista");
        btnverlista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverlistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombre)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnguardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btncancelar))
                            .addComponent(valorinicial)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fechainicial)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 46, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnverlista))))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorinicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechainicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardar)
                    .addComponent(btncancelar)
                    .addComponent(btnverlista, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        try {
            this.portafoliosGestor.add_portafolio(this.nombre.getText(),
                    Double.parseDouble(this.valorinicial.getText()),
                    this.fechainicial.getText());
            JOptionPane.showMessageDialog(this, "Se ha agregado portafolios con exito!");
            this.set_portafolios();
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Error al agregar portafolios!", "ERROR", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(PortafoliosForm.class.getName()).log(Level.SEVERE, null, ex);

        } catch (Exception edx) {
            JOptionPane.showMessageDialog(this, "Error al agregar portafolios!", "ERROR", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(PortafoliosForm.class.getName()).log(Level.SEVERE, null, edx);
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnverlistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverlistaActionPerformed
        try {
            this.set_portafolios();
        } catch (ParseException ex) {
            Logger.getLogger(PortafoliosForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnverlistaActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked

        this.set_selectedPortafolios();
       
    }//GEN-LAST:event_tablaMouseClicked

    private void tablaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaKeyPressed
       if(evt.getKeyCode() == evt.VK_ENTER){
            Object[] options = {"Guardar Cambios",
            "Cancelar",
            "Borrar"};
        int respuesta = JOptionPane.showOptionDialog(this, "¿Qué desea hacer?",
                "Confirmación", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE,
                null, options, options[2]);

        switch (respuesta) {

            case 0: // Guardar cambios       
            {
                try {
                    this.set_selectedPortafolios();
                    this.selectPortafolios.setValorinicial(Double.parseDouble(this.tabla.getValueAt(this.tabla.getSelectedRow(), 2).toString()));
                    this.selectPortafolios.setNombre(this.tabla.getValueAt(this.tabla.getSelectedRow(), 1).toString());
                    this.selectPortafolios.setFechacreacion(fecha_format.parse(this.tabla.getValueAt(this.tabla.getSelectedRow(), 3).toString()));
                    this.portafoliosGestor.update_portafolios(selectPortafolios);
                    this.set_portafolios();
                } catch (ParseException ex) {
                    Logger.getLogger(AportacionesForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (NonexistentEntityException ex) {
                    Logger.getLogger(AportacionesForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(AportacionesForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            break;
            case 1: //Cancelar,
                break;
            case 2: {
                try {
                    //Borrar
                    this.set_selectedPortafolios();
                    this.portafoliosGestor.delete_portafolio(this.selectPortafolios.getIdportafolios());
                    JOptionPane.showMessageDialog(this, "Se ha borrado el portafolios con ID: " + this.selectPortafolios.getIdportafolios(), "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                    this.set_portafolios();
                } catch (NonexistentEntityException ex) {
                    JOptionPane.showMessageDialog(this, "No se ha dado clic sobre la operacion!", "ERROR", JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(AportacionesForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ParseException ex) {
                    Logger.getLogger(AportacionesForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalOrphanException ex) {
                     JOptionPane.showMessageDialog(this, "No se ha podido borrar el portafolios, ya que tiene operaciones y/o resultadost!", "ERROR", JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(PortafoliosForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            break;

        }
       
       }
    }//GEN-LAST:event_tablaKeyPressed

    public DefaultTableModel fill_table() {

        Vector<String> colnames = new Vector<String>();
        colnames.add("ID");
        colnames.add("Nombre");
        colnames.add("Valor Inicial");
        colnames.add("Fecha de creación");

        return new DefaultTableModel(colnames, 4);
    }

    private void set_portafolios() throws ParseException {
        DefaultTableModel model = (DefaultTableModel) this.tabla.getModel();

        model = this.remove_rows(model);
        model.setNumRows(0);
        List<Portafolios> portafolios = this.portafoliosGestor.get_portafoliosList();

        for (int i = 0; i < portafolios.size(); i++) {
            model.addRow(new Object[]{
                portafolios.get(i).getIdportafolios(),
                portafolios.get(i).getNombre(),
                portafolios.get(i).getValorinicial(),
                fecha_format.format(portafolios.get(i).getFechacreacion())
            }
            );
        }
        this.tabla.setModel(model);
        this.tabla.revalidate();

    }

    private DefaultTableModel remove_rows(DefaultTableModel p_model) {

        for (int i = 0; i < p_model.getRowCount(); i++) {
            p_model.removeRow(i);
        }
        return p_model;
    }

    private void set_selectedPortafolios() {
        String var_nombre = this.tabla.getValueAt(this.tabla.getSelectedRow(), 1).toString();

        this.selectPortafolios = this.portafoliosGestor.find_portafoliosbyname(var_nombre);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnverlista;
    private javax.swing.JTextField fechainicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField valorinicial;
    // End of variables declaration//GEN-END:variables
}
