/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DAOsubScreens;

import DAO.OperacionGestor;
import DAO.PortafolioGestor;
import DAO.ResultadosGestor;
import com.xeiam.xchart.Chart;
import com.xeiam.xchart.ChartBuilder;
import com.xeiam.xchart.QuickChart;
import com.xeiam.xchart.Series;
import com.xeiam.xchart.SeriesMarker;
import com.xeiam.xchart.SwingWrapper;
import entity.Portafolios;
import entity.Resultados;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author 60044723
 */
public class PortafoliosInformation extends javax.swing.JPanel {

    /**
     * Creates new form PortafoliosInformation
     */
    private final PortafolioGestor portafoliosGestor;
    private final OperacionGestor  operacionGestor;
    private final ResultadosGestor resultadoGestor;
    private Portafolios selectedPortafolios;
    private final DateFormat fecha_format;
    public PortafoliosInformation(PortafolioGestor p_portafoliosGestor, OperacionGestor p_oprecionGestor,ResultadosGestor p_resultadogestor) {
        this.portafoliosGestor = p_portafoliosGestor;
        this.operacionGestor   = p_oprecionGestor;
        this.fecha_format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        this.resultadoGestor = p_resultadogestor;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbportafolios = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        btrefresh = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfvalorinicial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tftotalaportaciones = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tftotalretiros = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfvalortotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tffecha = new javax.swing.JTextField();
        btngrafica = new javax.swing.JToggleButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Información del Portafolios");

        cbportafolios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbportafolios.setModel(this.get_portafolios());
        cbportafolios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbportafoliosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Portafolios:");

        btrefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/refresh.png"))); // NOI18N
        btrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrefreshActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Valor inicial:");

        tfvalorinicial.setEditable(false);
        tfvalorinicial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Total Aportaciones:");

        tftotalaportaciones.setEditable(false);
        tftotalaportaciones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Total Retiros");

        tftotalretiros.setEditable(false);
        tftotalretiros.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Valor Total:");

        tfvalortotal.setEditable(false);
        tfvalortotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Fecha:");
        jLabel7.setMaximumSize(new java.awt.Dimension(68, 14));

        tffecha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tffecha.setText("2015-09-01 00:00:00");

        btngrafica.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btngrafica.setText("Grafica");
        btngrafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngraficaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbportafolios, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tffecha, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btngrafica, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfvalorinicial, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                    .addComponent(tftotalaportaciones)
                                    .addComponent(tftotalretiros)
                                    .addComponent(tfvalortotal))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btrefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbportafolios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tffecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfvalorinicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tftotalaportaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tftotalretiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfvalortotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(btngrafica, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrefreshActionPerformed
      this.cbportafolios.setModel(this.get_portafolios());
    }//GEN-LAST:event_btrefreshActionPerformed

    private void cbportafoliosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbportafoliosActionPerformed
        double var_valorinicial = 0 ;
        double var_aportaciones = 0;
        double var_retiros = 0;
        double var_total = 0;
        try {
            this.selectedPortafolios = this.portafoliosGestor.find_portafoliosbyname(this.cbportafolios.getSelectedItem().toString());
            var_valorinicial = this.selectedPortafolios.getValorinicial();
            var_aportaciones = this.operacionGestor.get_operaciones_totales(this.selectedPortafolios.getIdportafolios(),
                    this.fecha_format.parse(this.tffecha.getText()),
                    "AP");
            var_retiros      = this.operacionGestor.get_operaciones_totales(this.selectedPortafolios.getIdportafolios(),
                    this.fecha_format.parse(this.tffecha.getText()),
                    "RT");
        } catch (ParseException ex) {
            Logger.getLogger(PortafoliosInformation.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        var_total = var_valorinicial +var_aportaciones - var_retiros;
        
        this.tfvalorinicial.setText(new DecimalFormat("$#.##").format(var_valorinicial));
        this.tftotalaportaciones.setText(new DecimalFormat("$#.##").format(var_aportaciones));
        this.tftotalretiros.setText(new DecimalFormat("$#.##").format(var_retiros));
        this.tfvalortotal.setText(new DecimalFormat("$#.##").format(var_total));
    }//GEN-LAST:event_cbportafoliosActionPerformed

    private void btngraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngraficaActionPerformed
      Chart chart = new ChartBuilder().xAxisTitle("X").yAxisTitle("Y").width(600).height(400).build();
      chart.getStyleManager().setYAxisMin(-1000);
      chart.getStyleManager().setYAxisMax(5100);
      Series series = chart.addSeries(this.selectedPortafolios.getNombre(), null,this.generate_data_valor(this.resultadoGestor.get_aportacionesList(this.selectedPortafolios.getIdportafolios())) );
      series.setMarker(SeriesMarker.NONE);
     new SwingWrapper(chart).displayChartMatrix();
    }//GEN-LAST:event_btngraficaActionPerformed

    private double[] generate_data_valor(List<Resultados> resultados){
       
        double[] y = new double[resultados.size()];
        
        for (int i = 1; i < y.length; i++) {
      
            y[i] = resultados.get(i).getValor();
      
    }
       return y; 
    }
public DefaultComboBoxModel get_portafolios() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();

        List<Portafolios> portafolios = this.portafoliosGestor.get_portafoliosList();
        model.addElement(null);
        for (int i = 0; i < portafolios.size(); i++) {
            model.addElement(portafolios.get(i).getNombre());
        }

        return model;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btngrafica;
    private javax.swing.JButton btrefresh;
    private javax.swing.JComboBox cbportafolios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tffecha;
    private javax.swing.JTextField tftotalaportaciones;
    private javax.swing.JTextField tftotalretiros;
    private javax.swing.JTextField tfvalorinicial;
    private javax.swing.JTextField tfvalortotal;
    // End of variables declaration//GEN-END:variables
}
